-- MySQL Script generated by MySQL Workbench
-- Mon May 14 10:59:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema angular_roasts
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `angular_roasts` ;

-- -----------------------------------------------------
-- Schema angular_roasts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `angular_roasts` DEFAULT CHARACTER SET latin1 ;
USE `angular_roasts` ;

-- -----------------------------------------------------
-- Table `angular_roasts`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular_roasts`.`area` ;

CREATE TABLE IF NOT EXISTS `angular_roasts`.`area` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `country_idx` (`country` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `angular_roasts`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular_roasts`.`country` ;

CREATE TABLE IF NOT EXISTS `angular_roasts`.`country` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `angular_roasts`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular_roasts`.`profile` ;

CREATE TABLE IF NOT EXISTS `angular_roasts`.`profile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `angular_roasts`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular_roasts`.`region` ;

CREATE TABLE IF NOT EXISTS `angular_roasts`.`region` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `angular_roasts`.`roast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `angular_roasts`.`roast` ;

CREATE TABLE IF NOT EXISTS `angular_roasts`.`roast` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `creation` DATE NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `region` INT(11) NOT NULL,
  `country` INT(11) NULL DEFAULT NULL,
  `area` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `region_idx` (`region` ASC),
  INDEX `area_idx` (`area` ASC),
  INDEX `country_idx` (`country` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
