-- MySQL Script generated by MySQL Workbench
-- Tue May  8 12:19:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coffees
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `coffees` ;

-- -----------------------------------------------------
-- Schema coffees
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coffees` DEFAULT CHARACTER SET latin1 ;
USE `coffees` ;

-- -----------------------------------------------------
-- Table `coffees`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffees`.`area` ;

CREATE TABLE IF NOT EXISTS `coffees`.`area` (
  `area_id` INT(11) NOT NULL AUTO_INCREMENT,
  `a_name` VARCHAR(45) NULL DEFAULT NULL,
  `country` INT(11) NOT NULL,
  PRIMARY KEY (`area_id`),
  INDEX `country_idx` (`country` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffees`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffees`.`country` ;

CREATE TABLE IF NOT EXISTS `coffees`.`country` (
  `country_id` INT(11) NOT NULL AUTO_INCREMENT,
  `c_name` VARCHAR(45) NULL DEFAULT NULL,
  `geo_region` INT(11) NOT NULL,
  PRIMARY KEY (`country_id`),
  INDEX `geo_region_idx` (`geo_region` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffees`.`geo_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffees`.`geo_region` ;

CREATE TABLE IF NOT EXISTS `coffees`.`geo_region` (
  `geo_region_id` INT(11) NOT NULL,
  `g_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`geo_region_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffees`.`power_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffees`.`power_profile` ;

CREATE TABLE IF NOT EXISTS `coffees`.`power_profile` (
  `power_profile_id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TINYTEXT NULL DEFAULT NULL,
  `p_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`power_profile_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `coffees`.`roast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coffees`.`roast` ;

CREATE TABLE IF NOT EXISTS `coffees`.`roast` (
  `roast_id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_created` DATE NOT NULL,
  `weight` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  `power_profile` INT(11) NOT NULL DEFAULT '0',
  `geo_region` INT(11) NOT NULL DEFAULT '0',
  `country` INT(11) NULL DEFAULT '0',
  `area` INT(11) NULL DEFAULT '0',
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `r_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`roast_id`),
  INDEX `geo_region_idx` (`geo_region` ASC),
  INDEX `area_idx` (`area` ASC),
  INDEX `country_idx` (`country` ASC),
  INDEX `power_profile_idx` (`power_profile` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
